### ISSUE TITLE
Example 5-3 in Kubernetes Patterns, 2nd Edition

### ISSUE THREAD

**Issue by bmuschko** [k8spatterns/random-generator#2]
I tried create a Pod directly from the manifest in example 5-3.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: simple-random-generator
spec:
  containers:
  - image: k8spatterns/random-generator:1.0
    name: random-generator
    command:
    - "random-generator-runner"
    args:
    - "--seed"
    - "42"
```

It looks like the executable doesn't come with the container image.

```
Warning  Failed     2s (x3 over 18s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "random-generator-runner": executable file not found in $PATH: unknown
```

Is this meant to work as-is or is it a hypothetical example where the user has to assume that the executable does exist?
